### ISSUE TITLE
Unable to build with kotlin version 1.3.61

### ISSUE THREAD

**Issue by compscidr** [fabianishere/kotlin-plugin-generated#7]
Currently crashing during `./gradlew build` when used in my project with kotlin version 1.3.61:
```
e: java.lang.NoSuchMethodError: org.jetbrains.kotlin.com.intellij.openapi.extensions.impl.ExtensionPointImpl.registerExtension(Ljava/lang/Object;Lorg/jetbrains/kotlin/com/intellij/openapi/extensions/LoadingOrder;Lorg/jetbrains/kotlin/com/intellij/openapi/Disposable;)V
        at nl.fabianm.kotlin.plugin.generated.compiler.GeneratedPluginKt.registerExtensionAsFirst(GeneratedPlugin.kt:112)
        at nl.fabianm.kotlin.plugin.generated.compiler.GeneratedComponentRegistrar.registerProjectComponents(GeneratedPlugin.kt:97)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.registerExtensionsFromPlugins$cli(KotlinCoreEnvironment.kt:598)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$ProjectEnvironment.registerExtensionsFromPlugins(KotlinCoreEnvironment.kt:135)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:175)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:115)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:422)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.createCoreEnvironment(K2JVMCompiler.kt:263)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:152)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:55)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:84)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:42)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:104)
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:349)
        at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:105)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileIncrementally(IncrementalCompilerRunner.kt:237)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.access$compileIncrementally(IncrementalCompilerRunner.kt:37)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner$compile$2.invoke(IncrementalCompilerRunner.kt:79)
        at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:91)
        at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:606)
        at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:99)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1645)
        at sun.reflect.GeneratedMethodAccessor98.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
        at sun.rmi.transport.Transport$1.run(Transport.java:200)
        at sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by compscidr** [comment]
Downgrading to kotlin `1.3.50` makes it work - so perhaps something in kotlin changed.

**Comment by fabianishere** [comment]
Unfortunately, the plugin interface of the Kotlin compiler does not have a stable ABI. I have to rebuild the plugin for the 1.3.61 to get the plugin to work.

**Comment by compscidr** [comment]
> Unfortunately, the plugin interface of the Kotlin compiler does not have a stable ABI. I have to rebuild the plugin for the 1.3.61 to get the plugin to work.

Yeah makes sense, I found some posts in other projects which had some similar results. If you can point to me towards some documentation on how this needs to be done, I don't mind helping out with a fix.

**Comment by fabianishere** [comment]
See [this commit](https://github.com/fabianishere/kotlin-plugin-generated/commit/a66b9bd38de97ea843dd5e8a7f3a5743b8135f3b) that updates to Kotlin 1.3.50. Basically, it comes down to updating the Kotlin Gradle plugin to 1.3.61, setting the appropriate Kotlin IntelliJ plugin version and fixing the API changes that might occur when recompiling.

**Comment by fabianishere** [comment]
Fixed by #8

**Comment by compscidr** [comment]
Just an FYI - you'll have to generate the artifact and push it to the repo since I didn't have your credentials - then everything should work.

**Comment by fabianishere** [comment]
Thanks for the reminder. I was aware, but am unable to push them at the moment. Will do that later today :)
